// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsHyz0DsHoCYoqiBEfxp_eQmVn333rNNg',
    appId: '1:97418199469:web:c66a5d6bf8635e243ca124',
    messagingSenderId: '97418199469',
    projectId: 'summerclass2026-1-ba5e8',
    authDomain: 'summerclass2026-1-ba5e8.firebaseapp.com',
    storageBucket: 'summerclass2026-1-ba5e8.firebasestorage.app',
    measurementId: 'G-3XQ0WZV6QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXItoz6foeU9aFU3dhenpzOCVRTtz2Ho',
    appId: '1:97418199469:android:d42b285b05316f973ca124',
    messagingSenderId: '97418199469',
    projectId: 'summerclass2026-1-ba5e8',
    storageBucket: 'summerclass2026-1-ba5e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGTNoJGQW528QuCIeluXObQmpVeDBSdk',
    appId: '1:97418199469:ios:3e26546c5ac56afc3ca124',
    messagingSenderId: '97418199469',
    projectId: 'summerclass2026-1-ba5e8',
    storageBucket: 'summerclass2026-1-ba5e8.firebasestorage.app',
    iosBundleId: 'com.example.summerclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuGTNoJGQW528QuCIeluXObQmpVeDBSdk',
    appId: '1:97418199469:ios:3e26546c5ac56afc3ca124',
    messagingSenderId: '97418199469',
    projectId: 'summerclass2026-1-ba5e8',
    storageBucket: 'summerclass2026-1-ba5e8.firebasestorage.app',
    iosBundleId: 'com.example.summerclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsHyz0DsHoCYoqiBEfxp_eQmVn333rNNg',
    appId: '1:97418199469:web:2618f8e847cd41df3ca124',
    messagingSenderId: '97418199469',
    projectId: 'summerclass2026-1-ba5e8',
    authDomain: 'summerclass2026-1-ba5e8.firebaseapp.com',
    storageBucket: 'summerclass2026-1-ba5e8.firebasestorage.app',
    measurementId: 'G-TJDRNL793S',
  );
}
